"""Adicionar a coluna data_de_nascimento na tabela usuarios

Revision ID: 2502fcbbf40e
Revises: 150a5be7568a
Create Date: 2025-04-28 13:04:38.492698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2502fcbbf40e'
down_revision: Union[str, None] = '150a5be7568a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('data_de_nascimento', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'data_de_nascimento')
    # ### end Alembic commands ###
